### ISSUE TITLE
Question: about HidGuardian.

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#10]
HidGuardian hides the physical device and skips virtual devices from SCPVBD and ViGEm correct? Assuming it is a driver swap or UMD, what is its compatibility with FireShock?

Im closing this as soon as I submit it since its not really an "issue".

**Comment by nefarius** [comment]
Whoops, completely missed that one.

How HidGuardian works in detail is described in the repos README. Basically it's a small filter driver which sits "on top" of the HID device (can be FireShock, can be ViGEm, can be any physical Joypad) and answers every request to open the device with an access denied error code. Since it attaches to every HID device on the system, it uses the registry to lookup if the device it got attached to should be "guarded" or not.

In an essence the way it's designed as its own driver should ensure broad compatibility with every HID device. Hope I could clear things up.
