### ISSUE TITLE
API: Device Index vs. LED number in Xbox virtual devices

### ISSUE THREAD

**Issue by shauleiz** [nefarius/ViGEm#2]
I propose to drop the usage of device Serial Number and replace it by "LED" index (1 to 8).
The main reason is: LED index is system-wide unique.

As a result of this change, the API can expose the following functions:
* IsExist(LedN) - Does device (marked with LED index X) is installed on the system?
* IsOwned(LedN) - Was device (marked with LED index X) installed by this application or another one?
* PlugIn(LedN) - This one requires a change in the driver but I think it worthwhile because the user will be able to pre-define his device.

Currently, the API can tell the application the LED index of an owned device but there's not much we can do with it.

**Comment by nefarius** [comment]
The serial number isn't meant to be dealt with by the user of the API; that's why I introduced the `VIGEM_TARGET` object to abstract it away. Every device-related action is bound to this, the developer/end user doesn't need to know anything about the serial number. Also non-XUSB/XGIP devices don't report a LED index.

**Comment by shauleiz** [comment]
I understand.
Will there be a way, when it comes to Xbox device,  to access the LED index?
(In addition, I plan to comment on the VIGEM_TARGET object.)
