### ISSUE TITLE
2 events ok, 2 events nothing, cycles

### ISSUE THREAD

**Issue by rafaelvc** [nefarius/ViGEm#4]
Hello Nefarius... first congratulations for your cool work!!

Running the ViGEMTester with some modifications like: 
...
// First call press
r.wButtons = 1;
vigem_xusb_submit_report(x360, r);
Sleep(1000);
// First call release
r.wButtons = 0;
vigem_xusb_submit_report(x360, r);
Sleep(1000);
//------------

// Second call press
r.wButtons = 1;
vigem_xusb_submit_report(x360, r);
Sleep(1000);
// Second call release
r.wButtons = 0;
vigem_xusb_submit_report(x360, r);
Sleep(1000);
//-----------

// and so on for Third, Fourth, Fifth calls...  (simulating button press and release cycles with 1 sec of delay)
.....

First call does not generate events, second call generates (press/release events), third does not generate, fourth generates and so on...  resulting in cycles of (2 events ok, 2 events nothing, 2 events ok, 2 events nothing...). It is verified on Windows (Setup Usb Game Controllers -> Controller Xbox 360 for Windows -> Properties -> Tester)

It might not be issue itself. Is there something that I am missing ?

**Comment by nefarius** [comment]
Hi!

Thanks for testing :smile: I discovered this myself too; since I complete every request like I'm supposed to do I assume this "swallowing" of packets is a behavior of `XUSB.SYS` and not caused by my code. I don't really know if this is intentional design by Microsoft or a bug in their drivers. A workaround would be to simply complete two interrupt IRPs on every submit but I don't know if that's a bug or a possible feature :wink:

**Comment by rafaelvc** [comment]
Hi! Do you know what I have to setup to trace vigembus driver using dbgview ? I saw you doing it in one of your tweets :D

Is required something at 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ViGEmBus\ ?

Thank you!

**Comment by nefarius** [comment]
Buid as Debug, run DebugView as Administrator and select Capture Kernel. Then you should see all the debug messages.

**Comment by nefarius** [comment]
I can now confirm that this apparently is intended behavior of the `xusb22.sys` and nothing I can do.
